#+TITLE: Programming

* Youtube link: [[https://youtube.com/@freecodingclub][freecodingclub]]
All the videos of the sessions will be uploaded there.

* Type of programming languages
** procedural
- c
- c++
- python
** object oriented
- c++
- java
- python
** scripting
- bash
- perl
- batch (windows)
** functional
- F#

* Computer only understand binary language (0 or 1)
It consists of 0 and 1

- Source Code (Human readable code)
- Machine Code (format - 0 and 1) (read by computer)

* Compiler and Interpreter
- Compiled language - c++, c, etc.
- Intepreted languages - python, bash, batch, perl, etc.
    + Compiler and Interpreter convert the source code into machine code
*** Compiler
    - It translates the whole code at once
    - If there is any error, it will be caught by the compiler
*** Interpreter
    - It translates the code line by line
    - Errors are caught during the runtime

* How can we start?
- Compiler + editor
- gcc for c++, c
- vscode for editing the files (editor)

* Basic commands and codes used in todays session

#+begin_src c
#include<stdio.h>
int main(){
  printf("Hello, World\n");
  return 0;
}
#+end_src

#+begin_src c++
#include<iostream>
using namespace std;
int main(){
  cout<<"Hello, World"<<endl;
  return 0;
}
#+end_src

#+begin_src bash
#To compile c code use
gcc filename.c

#To compile c++ code use
g++ filename.c

#After compilation completed without any error type these to run your file
a           #if you are using command prompt
./a         #if you are using powershell
./a.out     #if you are using linux or macos
#+end_src

* For android users to setup termux and compiler
- [[https://github.com/termux/termux-app/releases/tag/v0.118.0][Download the termux from the link]]
- Install it in your device
- After install type the following command
  #+begin_src bash
  pkg update        #this will update your repository (only have to do it for the first time)
  #you can also use `apt update`
  #if it stuck at some percentage press enter, it will resume again

  #after all done type
  apt install clang     #this will install c and c+ compiler

  #type following to varify
  gcc -v    #for c compiler
  g++ -v    #for c++ compiler
  
  #+end_src
- Now you can use any terminal based editor like nano vim to writer code
- Type ~nano filename.c~
- Write your c code
- Type ~ctrl + x~ to exit (the shortcult will be there, look the bottom of your screen)
- It will ask you to save before exiting, press ~Y~ to save and press ~Enter~
- Now you can compile and run you code (check basic command section for commands)


* References
- [[https://www.youtube.com/watch?v=RTARink0Qe8][Day1 videos link]]
- [[https://www.ascii-code.com/][ASCII chart list]]
