#+TITLE: Learn to Code
#+Author: Abhishek Raj

* About me
| I am Abhishek Raj.                                                                                                                                              |
| I did my B.Tech from DCE, Darbhanga in Computer Science and Engineering (2018-2022)                                                                             |
| I love Linux, Programming, 3D Design and much more.                                                                                                             |
| I also enjoy teaching and I will be teaching you everything you need to know to get better in coding.                                                       |
| The main idea behind it is to build a strong community where we can help each other to get better in coding/programming or any other stuff related to computer. |
+ This is my social media handle
  - [[https://github.com/CISSSCO/][GitHub]]
  - [[mailto:cisssco581b@gmail.com][Gmail]]
  - [[https://www.linkedin.com/in/abhishek-raj-9b891415b/][LinkedIn]]
  - [[https://www.youtube.com/@cisssco][YouTube]]


* Requirements
This is for anyone who wants to know about coding/proramming.
This is a course related to programming, any laptop will do the job.
- A laptop
- Android + keyboard + otg (if you don't have a laptop)
- Internet

* Contents
These are the topics we will be covering in our upcoming sessions.
I will be adding more stuffs as needed.

** Programming
*** C/C++
  + We will be starting with c/c++.
  + I believe once you know this language, it won't be difficult to pick the others.
  + The main idea to start with c/c++ is that the first year students studing in colleges will benefit from the course for their examination.

*** OOPS
  + After that we will move towards the most important concepts of c++ programming language called OOPS.
  + We will study the needs of oops and the main concept behind the oops like polymorphism, encapsulation, inheritence, abstration, etc.
  + We will also build some cool project in this section.

*** DSA
  + Then we will learn about the Data Structures and Algorithm.
  + Everybody is afraid of DSA and I was too when I was learning but I found a good guide and I will share all the knowledge I have with you guys too.

*** CP
  + We will also be practicing the competitive programming from the start.

*** Other languages
Once you know a language it becomes easier to learn the other one.
I will also be covering these languages, the main are Python and Java which are most required languages now a days.
  + Python
  + Java
  + C#, etc.

** Linux
 - Command Line Interface basics
 - Setting up environment
 - Virtualization
 - Scripting
   + bash
   + batch
   + perl
 - System Administration
 - Version control
 - DevOps fundamentals

** Web Development
I also have plans for covering web dev in our course.
 - HTML
 - CSS
 - Javascript
 - Database, etc.

* Thanks
All the sessions will be live on google meet or any other video conferencing software.
 - The live session will be uploaded to youtube. You can watch it as many times as you want.
 - The session will be of 1 to 2 hrs max 3 to 4 times a week.
 - We will discuss the time before the class. Mostly it will be in evening, it might change according to our needs.
 - I will encourage you to get a laptop of your own otherwise I also have a solution for that too.
