#+TITLE: Introduction to Programming / LearnToCode

* Hello, World Code breakdown
#+begin_src c
#include<stdio.h>
int main(){
  printf("Hello, World\n");
  return 0;
}
#+end_src

- Here ~stdio.h~ is a header file (this should be included everytime before writing anything in your c program)
- ~printf()~ is a function which allows us to print something on screen
- All your code must be inside the main function for now.
- ~return 0~ should be the last line of your code inside the main function (anything after ~return 0~ will not be considered by the compiler)

* Input/Output
** In C
- ~printf()~ is used to print something to the output screen
- ~scanf()~ is used to take input from the user
** In c++
- ~cout<<~ is used to print something to the screen
- ~cin>>~ is used to take input from the user

* Data types
It is used to define the types of data we will be using in our program.
These are the main data types we will be dealing in our program -
- ~int~ used to store integers
- ~float~ used to store decimal value
- ~char~ used to store character
- ~double~ used to store larger decimal value

We will see the details of every one of them later in our program.

* Format specifier
These are placeholders that is used in place of our data types to be used in our program.
- ~%d~ for integer
- ~%f~ for float
- ~%c~ for character
- ~%lf~ for double

* Sum program
#+begin_src c
#include<stdio.h>
int main(){
  int a, b;     //initializing the variables
  printf("Enter two numbers: ");    //asking the users for input
  scanf("%d %d", &a, &b);           //taking input from user and storing it in our variable
  int c = a + b;     //initializing another variable and defining it to store sum of a and b
  print("Sum : %d", c);         //printing the sum to the output screen
  return 0;

}

#+end_src

* References
** Youtube link: [[https://youtube.com/@freecodingclub][freecodingclub]]
All the videos of the sessions will be uploaded there.
